#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

if [ -f "$HOME/.vimrc" ]; then
    mv "$HOME/.vimrc" "$HOME/.vimrc.bak"
fi
ln -fs $DIR/.vimrc ~/.vimrc

# Check if Vundle is already installed
if [ -d "$HOME/.vim/bundle/Vundle.vim" ]; then
    echo "Vundle already installed. Updating..."
    cd "$HOME/.vim/bundle/Vundle.vim" && git pull
else
    echo "Cloning Vundle..."
    git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
fi

mkdir -p ~/.vim/colors
curl -fsSL https://raw.githubusercontent.com/altercation/vim-colors-solarized/master/colors/solarized.vim -o ~/.vim/colors/solarized.vim

vim +PluginInstall +qall